<?php

namespace App\Http\Controllers;

use App\Models\Supply;
use App\Models\Category;
use App\Models\Department;
use App\Models\DeployedItem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class SupplyController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        // Debug: Log the request parameters
        \Log::info('SupplyController@index', ['request' => $request->all()]);
        
        // Create a new query builder instance
        $query = Supply::query();
        
        // Eager load relationships
        $query->with(['category']);
        
        // Apply search filter if provided
        if ($request->filled('search')) {
            $search = $request->input('search');
            $query->where(function($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('description', 'like', "%{$search}%")
                  ->orWhere('itemID', 'like', "%{$search}%");
            });
        }
        
        // Execute the query with pagination, ordered by itemID ascending
        $supplies = $query->orderBy('itemID', 'asc')->paginate(10)
            ->appends($request->query());
        
        // Debug: Log the query SQL and bindings
        \Log::info('Supply Query', [
            'sql' => $query->toSql(),
            'bindings' => $query->getBindings(),
            'supplies_type' => get_class($supplies),
            'supplies_count' => $supplies->count(),
            'supplies_total' => $supplies->total()
        ]);
        
        return view('supplies.index', compact('supplies'));
    }

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Show the deployment form.
     */
    public function deployForm()
    {
        // Check if DeployedItem model exists and is accessible
        if (!class_exists(DeployedItem::class)) {
            throw new \RuntimeException('DeployedItem model class not found');
        }
        
        // DeployedID will be auto-generated by the database
        // No need to generate it manually anymore
        
        // Get departments for the dropdown
        $departments = Department::orderBy('officename')->get();
        
        // Get categories for the dropdown
        $categories = Category::orderBy('categoryName')->get();
        
        // Get supplies for the dropdown
        $supplies = Supply::orderBy('name')->get();
        
        return view('supplies.deploy', [
            'departments' => $departments,
            'categories' => $categories,
            'supplies' => $supplies
        ]);
    }
    
    /**assss
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::orderBy('categoryName')->get();
        return view('supplies.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'description' => 'nullable|string',
            'acquired_at' => 'required|date',
            'estimated_life' => 'nullable|string',
            'unit_cost' => 'required|numeric',
            'category_id' => 'required|exists:categories,categoryID',
            'quantity' => 'required|integer|min:0',
            'minimum_stock' => 'required|integer|min:0',
            'amount' => 'required|numeric|min:0',
            'fund_code' => 'required|string|max:255',
            'pp_sub_account' => 'required|string|max:255',
            'gl_code' => 'required|string|max:255',
        ]);

        // Set the added_by field to the current authenticated user
        $validated['added_by'] = auth()->id();
        
        try {
            $supply = Supply::create($validated);
            
            return redirect()
                ->route('supplies.index')
                ->with('success', 'Supply created successfully.');
        } catch (\Exception $e) {
            return redirect()
                ->back()
                ->withInput()
                ->with('error', 'An error occurred while creating the supply. Please try again.');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Supply $supply)
    {
        $supply->load(['category', 'department']);
        return view('supplies.show', compact('supply'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Supply $supply)
    {
        $categories = Category::orderBy('categoryName')->get();
        return view('supplies.edit', compact('supply', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Supply $supply)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'description' => 'nullable|string',
            'acquired_at' => 'required|date',
            'estimated_life' => 'nullable|string',
            'unit_cost' => 'required|numeric|min:0',
            'quantity' => 'required|integer|min:0',
            'minimum_stock' => 'required|integer|min:0',
            'amount' => 'required|numeric|min:0',
            'category_id' => 'required|exists:categories,categoryID',
            'fund_code' => 'required|string|max:255',
            'pp_sub_account' => 'required|string|max:255',
            'gl_code' => 'required|string|max:255',
            'added_by' => 'required|exists:users,id'
        ]);
        
        $supply->update($validated);
        
        return redirect()
            ->route('supplies.index')
            ->with('success', 'Supply updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Supply $supply)
    {
        try {
            DB::beginTransaction();
            
            // Check if there are any related transactions
            if ($supply->transactions()->exists()) {
                return redirect()
                    ->route('supplies.index')
                    ->with('error', 'Cannot delete supply with existing transactions.');
            }

            $supply->delete();
            DB::commit();

            return redirect()
                ->route('supplies.index')
                ->with('success', 'Supply deleted successfully.');
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()
                ->route('supplies.index')
                ->with('error', 'An error occurred while deleting the supply.');
        }
    }
    
    /**
     * Display a listing of archived supplies.
     *
     * @return \Illuminate\View\View
     */
    public function archived()
    {
        $supplies = Supply::onlyTrashed()
            ->with(['category', 'department'])
            ->orderBy('deleted_at', 'desc')
            ->paginate(10);
            
        return view('supplies.archived', compact('supplies'));
    }
    
    /**
     * Archive the specified supply.
     *
     * @param  \App\Models\Supply  $supply
     * @return \Illuminate\Http\RedirectResponse
     */
    public function archive(Supply $supply)
    {
        try {
            $supply->delete();
            
            return redirect()
                ->route('supplies.index')
                ->with('success', 'Supply archived successfully.');
        } catch (\Exception $e) {
            return redirect()
                ->route('supplies.index')
                ->with('error', 'An error occurred while archiving the supply.');
        }
    }
    
    /**
     * Restore the specified archived supply.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function restore($id)
    {
        try {
            $supply = Supply::onlyTrashed()->findOrFail($id);
            $supply->restore();
            
            return redirect()
                ->route('supplies.archived')
                ->with('success', 'Supply restored successfully.');
        } catch (\Exception $e) {
            return redirect()
                ->route('supplies.archived')
                ->with('error', 'An error occurred while restoring the supply.');
        }
    }
    
    /**
     * Permanently delete the specified archived supply.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function forceDelete($id)
    {
        try {
            $supply = Supply::onlyTrashed()->findOrFail($id);
            
            // Check if there are any related transactions
            if ($supply->transactions()->exists()) {
                return redirect()
                    ->route('supplies.archived')
                    ->with('error', 'Cannot permanently delete supply with existing transactions.');
            }
            
            $supply->forceDelete();
            
            return redirect()
                ->route('supplies.archived')
                ->with('success', 'Supply permanently deleted.');
        } catch (\Exception $e) {
            return redirect()
                ->route('supplies.archived')
                ->with('error', 'An error occurred while permanently deleting the supply.');
        }
    }
} 